name: dart_web_toolkit_showcase
version: 0.3.14
description: >
  Dart Web Toolkit Showcase presents Dart Web Toolkit and Lost Dart features.
authors:
- Sergey Akopkokhyants <akserg@gmail.com>
homepage: http://akserg.github.com/dart_web_toolkit_showcase
dependencies:
  intl: ">=0.5.16"
  lost_dart: ">=0.4.12"
  dart_web_toolkit: ">=0.3.14+1"
