name: dart_web_toolkit_showcase
version: 0.2.1
description: >
  Dart Web Toolkit Showcase presents Dart Web Toolkit and Lost Dart features.
authors:
- Sergey Akopkokhyants <akserg@gmail.com>
homepage: http://akserg.github.com/dart_web_toolkit_showcase
dependencies:
  intl: ">=0.4.2"
  lost_dart: ">=0.4.4"
  dart_web_toolkit: ">=0.2.63"
