name: dart_web_toolkit_showcase
version: 0.1.0
description: >
  Dart Web Toolkit (DWT) Showcase.
authors:
- Sergey Akopkokhyants <akserg@gmail.com>
homepage: http://akserg.github.com/dart_web_toolkit_showcase
dependencies:
  intl: 0.2.10+1